### ISSUE TITLE
El contrato no está modificando el precio para DAI de los NFT

### ISSUE THREAD

**Issue by saver-community** [facundocarballo/saver-community#1]
En el contrato de prueba si se puede cambiar el precio para adquirir NFT desde el Admin. Pero en el oficial no permite cambiar el valor de DAI. Aunque se modifica bien en Admin luego a la hora de crear dice que tiene Dai insuficiente
![Dai insuficiente para crear NFT](https://github.com/facundocarballo/saver-community/assets/107320653/5ef7cce9-8bcb-45cf-bb86-f9e2f7f4ebdf)

**Comment by facundocarballo** [comment]
El contrato si modifica los precios, el error es de web que no los esta leyendo correctamente.
