### ISSUE TITLE
No se corresponde la cantidad de ciclos calificados en la barra del Premio Able

### ISSUE THREAD

**Issue by saver-community** [facundocarballo/saver-community#3]
![Incongruencia en la cantidad de ciclos calificados en la barra](https://github.com/facundocarballo/saver-community/assets/107320653/2b89bb11-ffd8-468c-abfa-0902bbe10c4d)
![Uploading Incongruencia en la cantidad de ciclos calificados en la barra.jpg…]()
Pienso que puede ser porque modifiqué en el Admin la cantidad de ciclos para ganar el Premio Able de 21 ciclo a 29 . O quizá no sea por eso . Habría que revisar. pero debe ser un tema de la web

**Comment by facundocarballo** [comment]
Efectivamente es por el cambio de la cantidad de ciclos necesarios para recibir el Premio Able.

El contrato de Able cada vez que una cuenta pasa de estar descalificada a estar calificada, toma el ciclo actual y le sume la cantidad de ciclos necesarios para conseguir el Premio Able.
> De esta forma obtenemos el ciclo en el que podrá recibir el Premio Able.

Si por algun motivo la cuenta se descalifica, y luego se vuelve a calificar ese ciclo objetivo cambiara.

---

Por ende, esas incongruencias con la web es por ese cambio de ciclos necesarios para obtener el Premio Able. Ya que la web hace lo siguiente:
- A = Obtiene la cantidad de ciclos necesarios para recibir el Premio Able. (actualmente 29, anteriormente 21)
- B = Obtiene el ciclo objetivo del usuario.
- C = Obtiene el ciclo actual del contrato.

Y realiza el siguiente calculo para obtener los días que lleva jugando:
> CICLOS JUGANDO = A - (B - C)
