### ISSUE TITLE
Incongruencia en el cartel de la web para publicar Able en las listas

### ISSUE THREAD

**Issue by saver-community** [facundocarballo/saver-community#5]
En ésta cuenta que tiene 3899 able dice que no tiene el mínimo de 150 Able para poder publicar Able a la venta
![Uploading Captura de pantalla (16).png…]()
![Uploading Captura de pantalla (17).png…]()

**Comment by facundocarballo** [comment]
Intente corregir el error, no pude replicarlo.

Espero que con este arreglo en el codigo quede resuelto, cualquier cosa volvemos a abrir el Issue.

**Comment by saver-community** [comment]
![Uploading Captura de pantalla (16).png…]()
